### ISSUE TITLE
too few picked mips ?

### ISSUE THREAD

**Issue by zd1** [shendurelab/MIPGEN#11]
Dear MIPGEN developers, 

I was trying to design MIPs for the following two regions using mipgen
chr10   123276883   123276903   FGFR2_1
chr10   123279667   123279687   FGFR2_2

I used the following parameter settings to run the tool 

mipgen -regions_to_scan test.bed \
-project_name test \
-arm_length_sums 40 \
-bwa_genome_index hg19.fa \
-min_capture_size 140 \
-max_capture_size 160 \
-snp_file dbsnp/All_20150415.vcf.gz

It turns out I only had the following two mips designed

> mip_key    logistic_score  chr ext_probe_start ext_probe_stop  ext_probe_copy  ext_probe_sequence  lig_probe_start lig_probe_stop  lig_probe_copy  lig_probe_sequence  mip_scan_start_position mip_scan_stop_position  scan_target_sequence    mip_sequence    feature_start_position  feature_stop_position   probe_strand    failure_flags   mip_name
> 10:123276832-123276971/17,23/-  0.964472    10  123276955   123276971   1   GGTGTTAACACCACGGA   123276832   123276854   1   GCATGGTTGACAGTTCTGCCAGG 123276855   123276954   CAAAGAGATTGAGGTTCTCTATATTCGGAATGTAACTTTTGAGGACGCTGGGGAATATACGTGCTTGGCGGGTAATTCTATTGGGATATCCTTTCACTCT    GCATGGTTGACAGTTCTGCCAGGCTTCAGCTTCCCGATATCCGACGGTAGTGTNNNNNGGTGTTAACACCACGGA 123276883   123276903   -   000 45_FGFR2_exon5_p.C227S_0001_SNP_a
> 10:123279651-123279790/16,24/+  0.857426    10  123279651   123279666   1   CGGCTTGGAGGATGGG    123279767   123279790   1   AGTGACCTCATGCCAGAAAAGCCT    123279667   123279766   CCGGTGAGGCGATCGCTCTGGTGGAGAGAGGGAAGAAAGGAGGAGTGGGGATGGGAGAATGAGAGACCAATAAATAAGCTGTGTTGTCCAGAGGGCTGTC    AGTGACCTCATGCCAGAAAAGCCTCTTCAGCTTCCCGATATCCGACGGTAGTGTNNNNNCGGCTTGGAGGATGGG 123279667   123279687   +   000 49_FGFR2_exon4_p.S137W_0002

I was just wondering what criteria were used in selecting the mips? as there are also others with a high logistic score in the test.all_mips.txt file, although some align to multiple regions in the genome.  We'd like to design double tiled mips for the whole region and would appreciate any advice on tuning the parameters. 

Many thanks, 

Best, 

Zhihao

**Comment by bethmartin** [comment]
Those two regions are only 20bp each. Did you actually mean to capture more than that? There is a -double_tile_strands_separately option that you can add to your command line, which should give you a mip on each strand.

**Comment by zd1** [comment]
Thanks a lot for your vary rapid reply. In this case I actually only need to quantify one base, which is at the centre of these two regions, and I just added some flanking basepairs. I am not entirely sure what the best practice is so any advice would be very welcomed! 

I switched on the double tile strands option and got the following 4 mips

10:123276822-123276973/22,18/+	0.89203	10	123276822	123276843	1	ACAGTATATACCTGGCAGAACT	123276956	123276973	1	CCGTGGTGTTAACACCGG	123276844	123276955	GTCAACCATGCAGAGTGAAAGGATATCCCAATAGAATTACCCGCCAAGCACGTATATTCCCCAGCGTCCTCAAAAGTTACATTCCGAATATAGAGAACCTCAATCTCTTTGT	CCGTGGTGTTAACACCGGCTTCAGCTTCCCGATATCCGACGGTAGTGTNNNNNACAGTATATACCTGGCAGAACT	123276883	123276903	+	000	45_FGFR2_exon5_p.C227S_0001_SNP_a
10:123276820-123276971/16,24/-	0.859269	10	123276956	123276971	1	GGTGTTAACACCACGG	123276820	123276843	1	AGTTCTGCCAGGTATATACTGTT	123276844	123276955	ACAAAGAGATTGAGGTTCTCTATATTCGGAATGTAACTTTTGAGGACGCTGGGGAATATACGTGCTTGGCGGGTAATTCTATTGGGATATCCTTTCACTCTGCATGGTTGAC	AGTTCTGCCAGGTATATACTGTTCCTTCAGCTTCCCGATATCCGACGGTAGTGTNNNNNGGTGTTAACACCACGG	123276883	123276903	-	000	45_FGFR2_exon5_p.C227S_0002_SNP_a
10:123279651-123279802/16,24/+	0.88996	10	123279651	123279666	1	CGGCTTGGAGGATGGG	123279779	123279802	1	CCAGAAAAGCCTCAAGCCTGCTGG	123279667	123279778	CCGGTGAGGCGATCGCTCTGGTGGAGAGAGGGAAGAAAGGAGGAGTGGGGATGGGAGAATGAGAGACCAATAAATAAGCTGTGTTGTCCAGAGGGCTGTCAGTGACCTCATG	CCAGAAAAGCCTCAAGCCTGCTGGCTTCAGCTTCCCGATATCCGACGGTAGTGTNNNNNCGGCTTGGAGGATGGG	123279667	123279687	+	000	49_FGFR2_exon4_p.S137W_0003_SNP_a
10:123279588-123279739/16,24/-	0.0818769	10	123279724	123279739	5	TTATTGGTCTCTCATT	123279588	123279611	1	TAGAGTTTGTCTGCAAGGTTTAC	123279612	123279723	CTCCCATCCCCACTCCTCCTTTCTTCCCTCTCTCCACCAGAGCGATCGCCTCACCGGCCCATCCTCCAAGCCGGACTGCCGGCAAATGCCTCCACAGTGGTCGGAGGAGACG	TAGAGTTTGTCTGCAAGGTTTACACTTCAGCTTCCCGATATCCGACGGTAGTGTNNNNNTTATTGGTCTCTCATT	123279667	123279687	-	000	49_FGFR2_exon4_p.S137W_0004

Is it possible to get more mips by tweaking things? 

Thanks very much, 
Zhihao

**Comment by bethmartin** [comment]
For that small of a region, you could just look at the "all_mips" output if you wanted more. :) Bigger regions would have more, overlapping mips. But for single specific base detection, you're already covered. Any more mips, and they could possibly start interfering with one another.

**Comment by zd1** [comment]
Thank you again for the reply. Would you mind suggesting a few rules for filtering the long list? I see that it is not always the case that a mip with a high logistic score and unique mapping would get picked. Manually screening each individual probe is probably not ideal. Any advice would be greatly appreciated!

Best, 
Zhihao

**Comment by bethmartin** [comment]
Maybe it would help to have a better sense of what you're trying to do and why you'd want to use mips in lieu of pcr to pick up just a couple of snps?

**Comment by zd1** [comment]
Hi again, 

In the four mips I got when I switched on double_tile_strands_separately, I realised that the last one had a logistic score 0.08 and aligns to 5 places in the genome. I am not quite sure why this one was selected. 

>mip_key	logistic_score	chr	ext_probe_start	ext_probe_stop	ext_probe_copy
10:123276822-123276973/22,18/+	0.89203	10	123276822	123276843	1
10:123276820-123276971/16,24/-	0.859269	10	123276956	123276971	1
10:123279651-123279802/16,24/+	0.88996	10	123279651	123279666	1
10:123279588-123279739/16,24/-	0.0818769	10	123279724	123279739	5

What we are trying to do here is to multiplex about 100 sites for the detection of very low level of somatic mosaicism using smMIPs. This is part of a validation of PCR hits, so we'd like to use a different technology.  So that's the reason why we had the flanking 10 basepairs on either side of the hit. 

For this we had a very long list of mips, ~200k,  in the "all_mip" file. It was not clear to us whether the logistic score best discriminates good ones from bad ones. Any help on how to shorten the list would be very appreciated!

Best,
Zhihao

**Comment by zd1** [comment]
Sorry to bother you again. By any chance if you could comment on your model, maybe in README or here, it'd be really helpful. We had half of our regions covered with a notable fraction of mips don't look right. Thanks!

**Comment by augustboyle** [comment]
That does seem like a problem. I don't know why the other strand is tiled with such low scoring MIPs.

I think the fastest way for me to assess what is happening would be for me to run your BED file myself and look at the output. I would suspect that there would be a lot of failure flags tripped due to SNPs in the region.

If you would like me to look at this, you can send the BED file to boylee@uw.edu .

Evan
