### ISSUE TITLE
RE Digest

### ISSUE THREAD

**Issue by rdoan** [shendurelab/MIPGEN#12]
Hello,

The MipGen extended data protocol states "NlaIII and StyD4I restriction digestion on the lambda digest in the presence of oligos complementary to the PCR adapters ". The methods to not explain if these oligos must be annealed prior to starting the digest or if you can simply mix them into the RE digest. 

Also, are there any issues of using the both the forward and reverse-complement of each MIP during this protocol (i.e. printing both sequences on the array pool)?

Thanks
Ryan

**Comment by augustboyle** [comment]
Hi Ryan,

When I did the digest, I annealed the oligos briefly (denaturing DNA and cooling to room temp) before adding the restriction enzymes. Don't forget about the overlap N nucleotides to the 3' end of one complementary oligo and the 5' end of the other.

We had envisioned problems associated with using both strands during the protocol, but work by others in the lab suggested that adding the reverse complement MIPs actually improved capture.

Just be aware that this might be dependent on the number of probes, i.e., with a small number it shouldn't matter, but it is possible (I have no evidence for this) that unintended products could predominate in larger pools. And of course, every troubled MIP pool is troubled in its own way, so if your sequences are biased in some way (such as towards low complexity sequences) that you might not anticipate, you may have to troubleshoot that.

Good luck!

Evan

**Comment by rdoan** [comment]
Hi Evan,

Thanks for the fast reply. For the annealing, did you simply denature at 95C for 2min and cool to RT? 

The complimentary oligos are simply the compliments of the added 20bp RE sites or do you add an extra N beyond the RE site in the oligos?
for example: 
my RE/primer site is TCCTGACACCTTCCAGCATG
my compliment oligo would be AGGACTGTGGAAGGTCGTACN

My concern for using both strands of MIPs is that they might anneal together before the RE digest.

Thanks,
Ryan

**Comment by augustboyle** [comment]
Sure,

Yes, that sounds right re: denaturing.

I added Ns beyond the restriction site. The enzymes typically need a few bases of overlap in order to bind and cut properly. I think I used 4 Ns, but I don't know how many are needed.

It is a reasonable concern, but I think it could be fine. Something worth testing!

Evan

**Comment by rdoan** [comment]
Hi Evan,

Thanks for the help!

Ryan
