### ISSUE TITLE
mipgen_pipeline_builder

### ISSUE THREAD

**Issue by rdoan** [shendurelab/MIPGEN#17]
Hello,

We have started to generate MIPs sequencing data and have begun to use the mipgen_pipeline_builder.py script. One question is on how to remove the extension and ligation arms from the fastq files. If I am correct, these need to be removed before mapping. Does this script perform the removal of the extension/ligation arms form the MIPs?

Also the script aborts at the first samtools step (conversion to bam) with the following output:

Has this error been observed before?

Thanks for your help!
Ryan

[main] Real time: 23.908 sec; CPU: 167.119 sec
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  -@, --threads INT
             Set number of sorting and compression threads [1]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]

**Comment by augustboyle** [comment]
Hi Ryan,

Actually, the extension and ligation arms are included in the mapping of the MIP reads to improve sensitivity and specificity. The arms are usually chosen to be at the more unique positions to prevent miscapture, so what we found was that trimming the arms in advance meant only mapping the insert region, which was less specific and often lead to zero map quality reads and mapping to targets that perfectly matched the insert sequence but had several mismatches to the targeting arms when they should be mapping to 1bp mismatches in the insert with perfect match to the targeting arms. The design pipeline also does not guarantee that the insert maps uniquely to the genome, but (by default) ensures at least hamming distance of 2 to the closest match when comparing the insert plus targeting arms.

As to the error, I have not seen it before, but I also haven’t run the analysis scripts in probably over a year! If you are using the latest htslib samtools, it might be that testing the 0.1.x versions would work. I have somehow ended up using samtools quite infrequently lately, so I can’t comment on what might have changed to make it incompatible with the script, if that’s what’s happening, but I recommend confirming that the SAM file looks correct and figuring out how to convert the SAM to BAM format. Then you can edit the builder output script to perform the conversion however you found works.

Good luck!
Evan

**Comment by rdoan** [comment]
Hi Evan,

Thanks for the help. We fixed the samtools error with a slight modification to the script. As for the mapping, since you leave the extension/ligation arms , do you trim them from the bam file? If so, is there a script provided with MipGen to do this?

Thanks
Ryan

**Comment by augustboyle** [comment]
Hi Ryan,

Great, glad you didn’t have any other problems.

The scripts that are run from the pipeline builder (i.e. the process of finding the unique reads/tag groups) should trim the targeting arms in the BAM file and update the fields in the BAM file so that only the insert region is described, so you should be good to go with the output files there!

Evan

**Comment by neurogene** [comment]
Hi evan
I am new to MIPgen.
how far will it effect if we don't remove the extension/ligation arms from the BAM files?
Gen

**Comment by augustboyle** [comment]
Well, the regions of the targeting arms would always be reference, or in the case of MIPs overlying common SNP nucleotides, always have alternate bases.

So around 30% of your targeted space would be prone to false negative calls, and maybe 1% would be prone to false positives if one out of 30 MIPs is a SNP MIP.

Evan
