### ISSUE TITLE
basic_string::substr error

### ISSUE THREAD

**Issue by augustboyle** [shendurelab/MIPGEN#2]
This is a very common error that is unfortunately difficult to pin down.

Usually it involves unanticipated whitespace in one of your input files either at the end of each line or at the end of the file. This commonly occurs in the BED file.

Another possibility is providing the directory of the bwa_genome_index instead of the file path. MIPgen attempts to read the fasta file briefly before beginning sequence retrieval and will throw this error if unsuccessful.

Ensure that your BED file is formatted properly and that the start and end coordinates are indeed valid.

**Comment by bradke** [comment]
Are there any characters (- . ; for example) in the locus name known to cause this error? I checked my BED file in TextPad with all the formatting characters visible and I don't see any white spaces, etc. For me, this error is showing up right after mipgen tells me "unable to tile sequences."

**Comment by augustboyle** [comment]
Hi,

I am not aware of any such character-related issues.

If the test example is working and your BED file is not, I recommend
deleting lines from your BED file to see if you can isolate which line(s)
are the problem. It’s usually something like having an incorrect chromosome
name or weird coordinates.

Evan


On October 11, 2016 at 8:12:42 AM, bradke (notifications@github.com) wrote:

Are there any characters (- . ; for example) in the locus name known to
cause this error? I checked my BED file in TextPad with all the formatting
characters visible and I don't see any white spaces, etc. For me, this
error is showing up right after mipgen tells me "unable to tile sequences."

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/2#issuecomment-252946838>,
or mute
the thread

**Comment by bradke** [comment]
Thanks! That did end up being the case.

**Comment by neilsonAG** [comment]
Ran into this issue as well. For me it turned out that some of the .bed entries had locations near the ends of scaffolds. I guess that this throws some sort of error when trying to span the region. The genomes I'm working with are highly fragmented so there were quite a few of these. A colleague wrote this quick test to highlight any .bed entries 100bp from the end of a scaffold.

```
from Bio import SeqIO
lengths = {}
for record in SeqIO.parse('genomic.fna', 'fasta'):
    lengths[record.id] = len(record.seq)
f = open('bedfile.bed')
for line in f.readlines():
    start = int(line.split()[1])
    stop = int(line.split()[2])
    contig = line.split()[0]
    if start < 100 or stop > lengths[contig]-100:
        print(line.strip())
```
