### ISSUE TITLE
ImportError: genome_sam_collapser.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

### ISSUE THREAD

**Issue by meganamsu** [shendurelab/MIPGEN#24]
I am running mipgen analysis for the first time on a new server. When attempting to run the following python script with appropriate flags and inputs:
python /MIPGEN/tools/mipgen_smmip_collapser.py

I receive the error below. Any insight? Is it an incompatibility with our version of python perhaps?
Traceback (most recent call last):
  File "/MIPGEN/tools/mipgen_smmip_collapser.py", line 10, in <module>
    from genome_sam_collapser import *
ImportError: /MIPGEN/tools/genome_sam_collapser.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

**Comment by augustboyle** [comment]
Hi Megan,  

I haven't seen that error before. I think it has to do with the characters in your input bed. Were you able to run the example dataset included in the download? If that runs successfully I would look very carefully at the text in your bed file to see if there were non alphanumeric characters, and test whether the code ran on the first few lines. If it runs on some but not all regions that suggests something is not formatted correctly somewhere in the file.  

Evan

**Comment by meganamsu** [comment]
Hi Evan,
I am running the final step in the data analysis pipeline (smmip_collapser), so input is: bam file, MIPs design file, and barcode file. I will check my MIPs design file. There's no bed file that I am aware of. Notably, I ran the command with a design file that has worked previously, and I still receive the same error. 
megan

**Comment by makirc** [comment]
Hi Megan,
It seems like this is a problem of using Python libraries compiled with your previous Python version on this new (incompatible) version (http://stackoverflow.com/questions/11878666/python-undefined-symbol-pyunicodeucs2-decodeutf8). You will need to compile the package that created genome_sam_collapser.so on the new system. If you are using both systems/both versions of Python, you might consider a fresh installation in a second folder. 
Good luck!
Martin
