### ISSUE TITLE
All logistic scores nan

### ISSUE THREAD

**Issue by nvanzuy** [shendurelab/MIPGEN#25]
I have run the mipgen_practice with the example commands but all of the logistic scores are '-nan'.  Is there a fix for this?

**Comment by augustboyle** [comment]
Hello,

I just did a fresh compile on a new machine and ran the example and didn’t
have any issues. Did you get any error messages? Changes in the various
bioinformatic tools could cause issues, but using the newest versions (plus
the versions following when MIPgen was released!) still seems to work fine
for the example.

Evan


On May 25, 2017 at 7:40:26 AM, nvanzuy (notifications@github.com) wrote:

I have run the mipgen_practice with the example commands but all of the
logistic scores are '-nan'. Is there a fix for this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/25>, or mute the thread

**Comment by nvanzuy** [comment]
Hi Evan,

 

This is my output from mipgen:

 

../mipgen -regions_to_scan practice_genes.bed -project_name practice_design -min_capture_size 162 -max_capture_size 162 -bwa_genome_index ../human_g1k_v37.fasta.gz

 

Program: bwa (alignment via Burrows-Wheeler transformation)

Version: 0.7.12-r1039

Contact: Heng Li <lh3@sanger.ac.uk>

 

Usage:   bwa <command> [options]

 

Command: index         index sequences in the FASTA format

         mem           BWA-MEM algorithm

         fastmap       identify super-maximal exact matches

         pemerge       merge overlapping paired ends (EXPERIMENTAL)

         aln           gapped/ungapped alignment

         samse         generate alignment (single ended)

         sampe         generate alignment (paired ended)

         bwasw         BWA-SW for long queries

 

         shm           manage indices in shared memory

         fa2pac        convert FASTA to PAC format

         pac2bwt       generate BWT from PAC

         pac2bwtgen    alternative algorithm for generating BWT

         bwtupdate     update .bwt to the new format

         bwt2sa        generate SA from BWT and Occ

 

Note: To use BWA, you need to first index the genome with `bwa index'.

      There are three alignment algorithms in BWA: `mem', `bwasw', and

      `aln/samse/sampe'. If you are not sure which to use, try `bwa mem'

      first. Please `man ./bwa.1' for the manual.

 

[mipgen] success on opening region file

[mipgen] features loaded; retrieving chromosomal sequence

 

Program: samtools (Tools for alignments in the SAM format)

Version: 0.1.19-96b5f2294a

 

Usage:   samtools <command> [options]

 

Command: view        SAM<->BAM conversion

         sort        sort alignment file

         mpileup     multi-way pileup

         depth       compute the depth

         faidx       index/extract FASTA

         tview       text alignment viewer

         index       index alignment

         idxstats    BAM index stats (r595 or later)

         fixmate     fix mate information

         flagstat    simple stats

         calmd       recalculate MD/NM tags and '=' bases

         merge       merge sorted alignments

         rmdup       remove PCR duplicates

         reheader    replace BAM header

         cat         concatenate BAMs

         bedcov      read depth per BED region

         targetcut   cut fosmid regions (for fosmid pool only)

         phase       phase heterozygotes

         bamshuf     shuffle and group alignments by name

 

[mipgen] first line of reference fasta reads: ­

  _____  

  _____  

RAZF���ˎd�qD���
  _____  

q�[1]g!����q!"n����a�,n�<�Ii��3�U�7���yd��������­��/���_�������=������������_��?�����/?��_���4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�{OUw��~��������w�u��s����������wZ~���o<D_�q��+=��g��c��{���ݯ­^����^ӳ�l�گ�^�f�~]|.�Ӧ�������.]��u�����i����}�s�}f��מs�z�u���lݑ�z̯�����w�\����a�u�T�f�0_c��|�F�����4z���ϲކ�!�p+@��9[rΏ��K�;q�sk?���[1]�X}����"��t�.��:}W �

                                                        ��­B�-Mm[/�s�ѫ�t.8�ʽ���4�YS=U�u�~�'֤��

  _____  

h

                  Ѷ6�=k��s[�u8��֭�֓�K�M��Ry�H�TO~]5��>�ؚ�װ^.&�,�x��v�����R�ֳ^�i����u��Z��k<�s��gd���1M�B�ϧ�g������u8j��NP�S�r7��[�x��

[mipgen] no masked feature file found

[mipgen] regions ready; accessing snp file

[mipgen] all 0 snps loaded; generating files for bwa

[bwa_aln] 17bp reads: max_diff = 2

[bwa_aln] 38bp reads: max_diff = 3

[bwa_aln] 64bp reads: max_diff = 4

[bwa_aln] 93bp reads: max_diff = 5

[bwa_aln] 124bp reads: max_diff = 6

[bwa_aln] 157bp reads: max_diff = 7

[bwa_aln] 190bp reads: max_diff = 8

[bwa_aln] 225bp reads: max_diff = 9

[bwa_aln] fail to locate the index

[bwa_sai2sam_se] fail to locate the index

[mipgen] sam file opened

[bwa_aln] 17bp reads: max_diff = 2

[bwa_aln] 38bp reads: max_diff = 3

[bwa_aln] 64bp reads: max_diff = 4

[bwa_aln] 93bp reads: max_diff = 5

[bwa_aln] 124bp reads: max_diff = 6

[bwa_aln] 157bp reads: max_diff = 7

[bwa_aln] 190bp reads: max_diff = 8

[bwa_aln] 225bp reads: max_diff = 9

[bwa_aln] fail to locate the index

[bwa_sai2sam_se] fail to locate the index

[mipgen] checking oligo copy

[mipgen] bwa copy number analysis finished

[mipgen] file of all mips ready for write: practice_design.all_mips.txt

[mipgen] file of collapsed mips ready for write: practice_design.collapsed_mips.txt

 

Then it lists the 64 features and outputs two files.

 

Thanks,

Natalie

**Comment by augustboyle** [comment]
Hi Natalie,

As the output suggests, the BWA index files are missing. You will need to
unzip the fasta (gunzip ../human_g1k_v37.fasta.gz), index the genome (bwa
index ../human_g1k_v37.fasta), and then enter the unzipped fasta in the
call to MIPgen ( -bwa_genome_index ../human_g1k_v37.fasta). Note that
creating the index for BWA should take a couple hours or so.

Then it looks like everything should work!

Best,
Evan

On May 26, 2017 at 3:34:10 AM, nvanzuy (notifications@github.com) wrote:

Hi Evan,



This is my output from mipgen:



../mipgen -regions_to_scan practice_genes.bed -project_name practice_design
-min_capture_size 162 -max_capture_size 162 -bwa_genome_index
../human_g1k_v37.fasta.gz



Program: bwa (alignment via Burrows-Wheeler transformation)

Version: 0.7.12-r1039

Contact: Heng Li <lh3@sanger.ac.uk>



Usage: bwa <command> [options]



Command: index index sequences in the FASTA format

mem BWA-MEM algorithm

fastmap identify super-maximal exact matches

pemerge merge overlapping paired ends (EXPERIMENTAL)

aln gapped/ungapped alignment

samse generate alignment (single ended)

sampe generate alignment (paired ended)

bwasw BWA-SW for long queries



shm manage indices in shared memory

fa2pac convert FASTA to PAC format

pac2bwt generate BWT from PAC

pac2bwtgen alternative algorithm for generating BWT

bwtupdate update .bwt to the new format

bwt2sa generate SA from BWT and Occ



Note: To use BWA, you need to first index the genome with `bwa index'.

There are three alignment algorithms in BWA: `mem', `bwasw', and

`aln/samse/sampe'. If you are not sure which to use, try `bwa mem'

first. Please `man ./bwa.1' for the manual.



[mipgen] success on opening region file

[mipgen] features loaded; retrieving chromosomal sequence



Program: samtools (Tools for alignments in the SAM format)

Version: 0.1.19-96b5f2294a



Usage: samtools <command> [options]



Command: view SAM<->BAM conversion

sort sort alignment file

mpileup multi-way pileup

depth compute the depth

faidx index/extract FASTA

tview text alignment viewer

index index alignment

idxstats BAM index stats (r595 or later)

fixmate fix mate information

flagstat simple stats

calmd recalculate MD/NM tags and '=' bases

merge merge sorted alignments

rmdup remove PCR duplicates

reheader replace BAM header

cat concatenate BAMs

bedcov read depth per BED region

targetcut cut fosmid regions (for fosmid pool only)

phase phase heterozygotes

bamshuf shuffle and group alignments by name



[mipgen] first line of reference fasta reads: ­

_____

_____

RAZF���ˎd�qD���
_____

q�[1]g!����q!"n����a�,n�<�Ii��3�U�7���yd��������­��/���_�������=������������_��?�����/?��_���4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�4�{OUw��~��������w�u��s����������wZ~���o<D_�q��+=��g��c��{���ݯ­^����^ӳ�l�گ�^�f�~]|.�Ӧ�������.]��u�����i����}�s�}f��מs�z�u���lݑ�z̯�����w�\����a�u�T�f�0_c��|�F�����4z���ϲކ�!�p+@��9[rΏ��K�;q�sk?���[1]�X}����"��t�.��:}W
�

��­B�-Mm[/�s�ѫ�t.8�ʽ���4�YS=U�u�~�'֤��

_____

h

Ѷ6�=k��s[�u8��֭�֓�K�M��Ry�H�TO~]5��>�ؚ�װ^.&�,�x��v�����R�ֳ^�i����u��Z��k<�s��gd���1M�B�ϧ�g������u8j��NP�S�r7��[�x��

[mipgen] no masked feature file found

[mipgen] regions ready; accessing snp file

[mipgen] all 0 snps loaded; generating files for bwa

[bwa_aln] 17bp reads: max_diff = 2

[bwa_aln] 38bp reads: max_diff = 3

[bwa_aln] 64bp reads: max_diff = 4

[bwa_aln] 93bp reads: max_diff = 5

[bwa_aln] 124bp reads: max_diff = 6

[bwa_aln] 157bp reads: max_diff = 7

[bwa_aln] 190bp reads: max_diff = 8

[bwa_aln] 225bp reads: max_diff = 9

[bwa_aln] fail to locate the index

[bwa_sai2sam_se] fail to locate the index

[mipgen] sam file opened

[bwa_aln] 17bp reads: max_diff = 2

[bwa_aln] 38bp reads: max_diff = 3

[bwa_aln] 64bp reads: max_diff = 4

[bwa_aln] 93bp reads: max_diff = 5

[bwa_aln] 124bp reads: max_diff = 6

[bwa_aln] 157bp reads: max_diff = 7

[bwa_aln] 190bp reads: max_diff = 8

[bwa_aln] 225bp reads: max_diff = 9

[bwa_aln] fail to locate the index

[bwa_sai2sam_se] fail to locate the index

[mipgen] checking oligo copy

[mipgen] bwa copy number analysis finished

[mipgen] file of all mips ready for write: practice_design.all_mips.txt

[mipgen] file of collapsed mips ready for write:
practice_design.collapsed_mips.txt



Then it lists the 64 features and outputs two files.



Thanks,

Natalie
