### ISSUE TITLE
All scores are NaN or low negative value

### ISSUE THREAD

**Issue by augustboyle** [shendurelab/MIPGEN#4]
Problems with scoring may have a few causes, including references with non-ACTG bases or not having enough flanking distance in your reference. Issues with the genome_dir option are common. I have attempted to fix this problem, but have yet to verify the fix.

**Comment by tobsecret** [comment]
This can also be a problem with the version of BWA, as explained in #33, older versions of BWA (in my case bwa 0.5.9) can cause only nan values to be in the score column. I was able to fix this by using a newer version of bwa (0.7.15).
