### ISSUE TITLE
Interested in a specific mutation but all smMIPs covering the region come up with low logistic scores

### ISSUE THREAD

**Issue by biokatrin** [shendurelab/MIPGEN#43]
Hi,

I have designed smMIPs for a specific mutation in the 5´ UTR of a gene but all the smMIPs (+/- 60 nt from the mutation) have low logistic scores. I have tested three of them, and they do not capture the region well enough. Is there a way to improve the design?  

I have set min. and max. capture size to 162, tag size to 8 and arm length sum is 40.

Thanks,

Katrin

**Comment by augustboyle** [comment]
Hi Katrin,

You can use a range of arm length sums. 20 is a little low. If your 5’ UTR is low GC then that could be the problem. The second option is to rebalance the particular MIP by increasing the concentration by 10-100 fold. If you don’t have a lot of off target sites competing with the on target site that works maybe half of the time.

Those are the ideas that come to mind. Low complexity regions are hard to capture with MIPs so it might be a case where you should simply remove that MIP from your assay.

Evan
