### ISSUE TITLE
Selecting Multiple MIPs per Site

### ISSUE THREAD

**Issue by RaviKBajpai** [shendurelab/MIPGEN#45]
Hi, I just want to say this is a really great program and I particularly love how customizable the options are within it. I am looking to design multiple MIPs (4-6) for a set of sites. I initially was hoping to do this by turning on both -double_tile_strands_separately and -double_tile_strand_unaware to get 4 MIPs but kept getting a segmentation error when I did this. Is it possible to run both these options on at the same time and my program is just set up incorrectly? If not is there any other settings I could use to get >2 MIPs per site? I was thinking about just trying to sort through the collapsed_mips file but there are around 600 MIPs per site which would be a little difficult to go through. Thanks!!

**Comment by augustboyle** [comment]
Hi,

Thanks for using MIPgen!

The code is designed to support using both options but from experience I know some regions introduce a lot of missing MIPs. The segmentation errors are hard to troubleshoot, but I would recommend trying one or a few regions at a time and seeing if it always happens or it is triggered by specific regions.  If your regions are close together it might be running out of bases to put the arms, especially depending on the other options you are using.

Best,
Evan Boyle
Postdoctoral scholar
UC San Diego

**Comment by RaviKBajpai** [comment]
Hey Evan, thanks for the quick reply! I actually took a deeper dive at the data and found that the size of the collapsed_mip file can be reduce a lot by filtering for repeat MIPs (leaving only 15-40 MIPs ish), so I think I might just use this file and then sort. I am attempting to tile a large array of sites so I think it would be difficult to find which sites are introducing the segmentation errors. 

The other question I wanted to ask you is how does the collapsed MIP file get filtered down into the picked MIP file and if you had any advice on how to pick the best MIPs (I'm currently using SVR score and arm copy number) Also what goes in the snp_mip file? Are they just the best alternate designs to avoid any SNP provided in the original command? Thanks for all your help!!

**Comment by augustboyle** [comment]
Hi, no problem.

Yes, there are lots of repeats in there. The process is a little complicated but the collapsed MIPs are used in an initial stage to pick the best MIPs for the worst scoring scan position to be captured. Once the best local MIPs are exhausted (which might not happen for shorter regions), it switches to a second phase (condensed MIPs) where it checks the best MIP per scan start position.

There are a lot of options controlling MIP picking in MIPgen. Depending on sequence complexity and number of MIPs (larger of either favors more stringency on arm copy number) you might pick differently.

The SNP MIP file accounts for the SNP VCF and outputs the MIPs that will capture an alternate allele. It only does this for biallelic sites, and it tries to avoid placing arms where SNPs are present.

Evan
