### ISSUE TITLE
The final step of the analysis did not respond, no error message was displayed, and only an empty file was generated.

### ISSUE THREAD

**Issue by zpc975571872** [shendurelab/MIPGEN#49]
Dear Even or his associate,

I hope this letter finds you well. I have a question that I would like to ask regarding an 
![IMG_20230402_160305](https://user-images.githubusercontent.com/102865799/229340353-83b57173-da73-4523-89fd-690559e04044.jpg)
issue I encountered during my analysis process. At the final step of my analysis, which involves the read and fold procedure, I encountered a problem where the 
![Uploading IMG_20230402_160305.jpg…]()
process seemed to get stuck. There were no error messages, but the generated file was empty and there were no results. Have you ever encountered a similar issue? Could you provide me with some guidance or suggestions?

I apologize for bothering you on the weekend and thank you in advance for any help you can provide.

Best regards,

Pengcheng Zhang

**Comment by augustboyle** [comment]
Hi Pengcheng,

I would say for new users, a newer MIP analysis pipeline would be the best place to start: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007956

The designing scripts should be robust, but the analysis steps were fairly lightweight and not the easiest to work with.

**Comment by zpc975571872** [comment]
Thanks，augustboyle!
    Thank you for your reply, the problem has been solved is python3 issue, not very compatible with scripts, now the problem is solved.
Thank you for your hard work
