### ISSUE TITLE
What is the reason for a difference in arm length between ligation and extension arms?

### ISSUE THREAD

**Issue by RoyBSimons** [shendurelab/MIPGEN#52]
Dear shendurelab,

I noticed that the ligation arm and extension arms are of different length.
Is there a reason to let the ligation arm bind earlier than the extension arm? 
In various MIP-studies the arms are of equal size.

Kind regards,
Roy

**Comment by augustboyle** [comment]
Hello,You can review the article to learn about optimal arm length: supplementary figure 3 shows that longer ligation arms relative to extension arms perform better! https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4155255/bin/supp_btu353_bioinformatics_supplemental4.docEvanCourtesy of my phoneOn Jul 18, 2023, at 1:45 AM, Roy Simons ***@***.***> wrote:﻿
Dear shendurelab,
I noticed that the ligation arm and extension arms are of different length.
Is there a reason to let the ligation arm bind earlier than the extension arm?
In various MIP-studies the arms are of equal size.
Kind regards,
Roy
