### ISSUE TITLE
Can MIPgen be used in mip design of aquatic animals?

### ISSUE THREAD

**Issue by Cockle01** [shendurelab/MIPGEN#53]
I want to know whether the model of MIPgen is only suitable for human exome, or anything interested.

**Comment by augustboyle** [comment]
Hello,MIPgen can be used on any genome assuming the chromosomes or contigs are large enough (around 100 extra nt around regions of interest for logistic scoring and 1000 nt for SVM)Evan On Aug 23, 2023, at 6:04 AM, Cockle01 ***@***.***> wrote:﻿
I want to know whether the model of MIPgen is only suitable for human exome, or anything interested.

**Comment by Cockle01** [comment]
Hello Evan, I still have a question about universal constant mip sequence. If I alter this sequence in mipgen.cpp, whether this will impact the performance of MIPgen design algorithm?


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "shendurelab/MIPGEN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 晚上9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shendurelab/MIPGEN] Can MIPgen be used in mip design of aquatic animals? (Issue #53)





 Hello,MIPgen can be used on any genome assuming the chromosomes or contigs are large enough (around 100 extra nt around regions of interest for logistic scoring and 1000 nt for SVM)Evan On Aug 23, 2023, at 6:04 AM, Cockle01 ***@***.***&gt; wrote:﻿ 
 I want to know whether the model of MIPgen is only suitable for human exome, or anything interested.

**Comment by augustboyle** [comment]
Hello,

The algorithm is entirely independent of the universal sequence used. I expect the universal sequence to have some effect on the accuracy of scoring, but we did not test this, and I would expect it to have a meaningful impact pretty infrequently.

>

**Comment by Cockle01** [comment]
Thank you so much, Evan! I will try and make some tests on it later. If MIPgen is still robust after the universal sequence changed, I will give you a reply :)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shendurelab/MIPGEN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月6日(星期三) 凌晨2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shendurelab/MIPGEN] Can MIPgen be used in mip design of aquatic animals? (Issue #53)





 Hello, 
 
 The algorithm is entirely independent of the universal sequence used. I expect the universal sequence to have some effect on the accuracy of scoring, but we did not test this, and I would expect it to have a meaningful impact pretty infrequently. 
 
 &gt;  
 &gt; On Mar 5, 2024, at 4:36 AM, Cockle01 ***@***.***&gt; wrote: 
 &gt;  
 &gt; ﻿ 
 &gt; Hello Evan, I still have a question about universal constant mip sequence. If I alter this sequence in mipgen.cpp, whether this will impact the performance of MIPgen design algorithm? 
 &gt;  
 &gt;  
 &gt; ------------------ 原始邮件 -------------

**Comment by Cockle01** [comment]
Hello Evan, I tried to modify the universal sequence in MIPgen.cpp into my expected one and it worked with MIPgen's test data. Picked mips file was generated while some error in it that all the logistic score were nan. The copy number of ext/lig probe also changed to zero. I am not ensure whether such mips can be used into further experiment or maybe other places in script need to be improved.

**Comment by Cockle01** [comment]
Hello Evan, I found I made some error in input file. Now MIPgen can run normally. The logistic score and copy number are also shown.  I found that the picked mip generated after I changed universal sequence is same as the previous one completely.
