### ISSUE TITLE
Long inserts

### ISSUE THREAD

**Issue by Malabady** [shendurelab/MIPGEN#54]
Hello,

Is there any limitations on the target insert size? I want to design high density MIPS for small genome with insert length target > 1300. Is this possible? If yes, do you have any recommendations about the parameters that I should adjust? 

Thanks,

**Comment by augustboyle** [comment]
Hello,The training set should enable decent performance up to 250 nt inserts. At your intended size I don’t think the scoring will be very accurate. That said the functionality may still be useful for rolling regions if you are targeting a large number of loci. I would advise using a narrow range of parameters so the probes are more similar to each other and the scoring does not play a large role in selection.EvanCourtesy of my phoneOn Oct 23, 2023, at 12:49 PM, Malabady ***@***.***> wrote:﻿
Hello,
Is there any limitations on the target insert size? I want to design high density MIPS for small genome with insert length target > 1300. Is this possible? If yes, do you have any recommendations about the parameters that I should adjust?
Thanks,

**Comment by Malabady** [comment]
Thanks! 

what do you think about the following parameters:

./mipgen -regions_to_scan WG.bed  \
-project_name SC2-design \
-min_capture_size 1000 \
-max_capture_size 1500 \
-bwa_genome_index genome.fasta \
-capture_increment 1 \
-max_mip_overlap 900 \
-check_copy_number off \
-double_tile_strands_separately on \
-target_arm_copy 30

I am designing for the whole genome, which is only 30Kb genome. So, it is once locus.  What would you change in these parameters? 

Many thanks,

**Comment by augustboyle** [comment]
Hello,I thought I would follow up and say that I didn’t see any big issues with those options but of course I couldn’t say whether they will satisfy your use case in the end!Best of luck,EvanCourtesy of my phoneOn Oct 23, 2023, at 6:08 PM, Malabady ***@***.***> wrote:﻿
Thanks!
what do you think about the following parameters:
./mipgen -regions_to_scan WG.bed  
-project_name SC2-design 
-min_capture_size 1000 
-max_capture_size 1500 
-bwa_genome_index genome.fasta 
-capture_increment 1 
-max_mip_overlap 900 
-check_copy_number off 
-double_tile_strands_separately on 
-target_arm_copy 30
I am designing for the whole genome, which is only 30Kb genome. So, it is once locus.  What would you change in these parameters?
Many thanks,
